import Link from "next/link";
import { ArrowRight, Radio, ShieldCheck, Upload, Users } from "lucide-react";
const modules = [
  { title: "Admin Dashboard", href: "/admin", icon: ShieldCheck, copy: "Run teams, queues, sold/unsold flows, audit logs, imports, and Telegram sends." },
  { title: "Manager Console", href: "/manager", icon: Users, copy: "Mobile-first bidding, roster, purse, skill balance, and next-bid eligibility." },
  { title: "TV Display", href: "/tv", icon: Radio, copy: "Full-screen live auction display with player card, timer, queue, and purse ticker." },
  { title: "Imports", href: "/admin#imports", icon: Upload, copy: "CSV upload surfaces for registration, CricHeroes stats, and kit image mapping." },
];
export default function Home() { return <main className="min-h-screen px-4 py-8 sm:px-6"><section className="mx-auto max-w-7xl"><div className="glass relative overflow-hidden rounded-[2rem] p-8 sm:p-12"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" /><p className="text-sm uppercase tracking-[.45em] text-cyan-200/70">EPL Auction Platform</p><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-tight sm:text-7xl">Production auction operations for cricket nights.</h1><p className="mt-5 max-w-2xl text-lg text-slate-300">Role-gated dashboards, live bidding rules, TV presentation, manager controls, CSV imports, audit trails, and Supabase-ready realtime architecture.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/admin" className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 shadow-glow">Open admin</Link><Link href="/tv" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-bold text-white">Open TV mode</Link></div></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{modules.map(({ title, href, icon: Icon, copy }) => <Link key={href} href={href} className="group glass rounded-[1.5rem] p-5 transition hover:-translate-y-1 hover:border-cyan-300/40"><Icon className="mb-5 text-cyan-300" /><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-sm text-slate-300">{copy}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-200">Open <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section></main>; }
